nodeLinker: hoisted
blockExoticSubdeps: false
allowBuilds:
  '@ffprobe-installer/linux-x64': true
  better-sqlite3: false
  canvas: false
  electron: true
  electron-winstaller: true
  esbuild: true
  ffmpeg-static: true
  sharp: true
